src/frontend/src/mockdata/markets.ts
https://linear.app/econia-labs/issue/ECO-815/have-default-trading-page-be-eapteusdc
=> [ECO-815] - Change default trading page to eAPT/eUSDC

README.md, src/frontend/src/components/trade/OrdersTable.tsx, src/frontend/src/components/trade/TradeHistoryTable.tsx, src/frontend/src/pages/trade/[market_name].tsx, src/frontend/src/types/api.ts
https://linear.app/econia-labs/issue/ECO-835/integrate-orders-list-api
=> [ECO-835] - Update orders table

src/frontend/src/components/StatsBar.tsx, src/frontend/src/components/trade/OrdersTable.tsx, src/frontend/src/components/trade/TradeHistoryTable.tsx, src/frontend/src/types/api.ts
Add AVG execution price, update nominal, add mock data for price info.
https://linear.app/econia-labs/issue/ECO-864/include-average-execution-price-in-orders-history-table
=> [ECO-864] - Include average execution price in orders history table

src/frontend/package.json, src/frontend/pnpm-lock.yaml, src/frontend/src/components/StatsBar.tsx, src/frontend/src/features/hooks.ts, src/frontend/src/features/priceStatsSlice.ts, src/frontend/src/pages/_app.tsx, src/frontend/src/store/store.ts, src/frontend/src/types/api.ts
Added redux
Add price stats to redux
=> [ECO-888] - Integrate price stats api

src/frontend/src/components/OrderbookTable.tsx, src/frontend/src/pages/trade/[market_name].tsx
https://linear.app/econia-labs/issue/ECO-898/fix-trade-history-height
=> [ECO-898] - Fix trade history table's height bug

src/frontend/src/components/trade/OrdersTable.tsx, src/frontend/src/types/api.ts, src/sdk/src/entry_functions.ts
https://linear.app/econia-labs/issue/ECO-862/implement-order-cancellation
=> [ECO-862] - Implement order cancellation

src/frontend/src/components/StatsBar.tsx, src/frontend/src/components/trade/DepositWithdrawModal/SelectMarketContent.tsx, src/frontend/src/components/trade/DepositWithdrawModal/index.tsx, src/frontend/src/components/trade/OrdersTable.tsx, src/frontend/src/hooks/useOrderbook.ts, src/frontend/src/types/api.ts
https://linear.app/econia-labs/issue/ECO-865/incorporate-market-selection-feature
=> [ECO-865] - Incorporate market selection feature

src/frontend/src/components/Header.tsx, src/frontend/src/components/Input.tsx, src/frontend/src/components/modals/content/DepositWithdrawContent.tsx, src/frontend/src/components/modals/flows/DepositWithdrawFlowModal.tsx, src/frontend/src/pages/faucet/index.tsx, src/frontend/src/pages/swap/index.tsx, src/frontend/src/pages/trade/[market_id].tsx, src/frontend/src/pages/trade/index.tsx, src/frontend/src/utils/helpers.ts
Clean up code, update Econia logo link.
=> [ECO-923] - Auto focus on amount input in deposit modal

src/frontend/src/components/Header.tsx, src/frontend/src/components/StatsBar.tsx, src/frontend/src/components/modals/flows/WalletButtonFlowModal.tsx, src/frontend/src/components/trade/DepositWithdrawModal/SelectMarketContent.tsx, src/frontend/src/components/trade/TVChartContainer.tsx, src/frontend/src/pages/faucet/index.tsx, src/frontend/src/pages/swap/index.tsx
https://linear.app/econia-labs/issue/ECO-924/update-market-metadata-formatting
=> [ECO-924] - Update market metadata formatting, update href from /trade to /market

src/frontend/src/components/trade/TradeHistoryTable.tsx, src/frontend/src/pages/market/[market_id].tsx
https://linear.app/econia-labs/issue/ECO-928/update-trade-history-table
=> [ECO-928] - Update trade history table

src/frontend/src/components/trade/OrdersTable.tsx, src/frontend/src/pages/market/[market_id].tsx
Update user orders table also (Task #927)
https://linear.app/econia-labs/issue/ECO-927/update-user-orders-table
=> [ECO-934] - Fix user orders issues

src/frontend/src/components/trade/DepositWithdrawModal/SelectMarketContent.tsx
https://linear.app/econia-labs/issue/ECO-926/update-market-selector-columns
=> [ECO-926] - Update market selector columns

src/frontend/src/components/StatsBar.tsx
Fix values that are 0
https://linear.app/econia-labs/issue/ECO-969/market-stats-bar-bug
=> [ECO-969] - Fix market stats bar bug

src/frontend/src/components/trade/OrdersTable.tsx
Add order=created_at.desc to get default orders from newest to oldest
https://linear.app/econia-labs/issue/ECO-970/update-orders-table-query
=> [ECO-970] - Update orders table query

src/frontend/src/components/AccountDetailsModal.tsx, src/frontend/src/components/MarketAccountCard.tsx, src/frontend/src/components/icons/ExitIcon.tsx
https://linear.app/econia-labs/issue/ECO-334/implement-account-details-market-accounts-modal
=> [ECO-334] - Market accounts component

src/frontend/src/components/Input.tsx, src/frontend/src/components/modals/content/DepositWithdrawContent.tsx, src/frontend/src/components/modals/flows/DepositWithdrawFlowModal.tsx
https://linear.app/econia-labs/issue/ECO-1035/fit-all-pop-up-windows-to-figma-size
=> [ECO-1035] - Update deposit/withdraw modal size

src/frontend/src/components/StatsBar.tsx, src/frontend/src/components/modals/flows/UnConnectedNotice.tsx, src/frontend/src/components/trade/DepositWithdrawModal/SelectMarketContent.tsx
This PR includes:
- Update notice popup sizing
- Update StatsBar
- Fix market selection modal
=> [ECO 1039] Fix market selection modal

src/frontend/src/components/StatsBar.tsx, src/frontend/src/pages/market/[market_id].tsx
https://linear.app/econia-labs/issue/ECO-1051/arrow-when-selecting-markets-needs-to-be-further-away
=> [ECO-1051] - Update select market arrow spacing

src/frontend/src/components/trade/OrdersTable.tsx, src/frontend/src/pages/market/[market_id].tsx
https://linear.app/econia-labs/issue/ECO-1038/fix-order-container-spacing-to-match-all-other-headers
=> [ECO-1038] - Update orders table spacing

src/frontend/src/components/trade/TradeHistoryTable.tsx
https://linear.app/econia-labs/issue/ECO-1040/color-price-for-trade-history
=> [ECO-1040] - Update color price for trade history

src/frontend/src/components/trade/OrdersTable.tsx
https://linear.app/econia-labs/issue/ECO-1046/what-is-this-toggle-for
=> [ECO-1046] - Orders table: remove sorting arrows

src/frontend/src/components/AccountDetailsModal.tsx, src/frontend/src/components/Button.tsx, src/frontend/src/components/modals/content/DepositWithdrawContent.tsx, src/frontend/src/components/modals/content/RegisterAccountContent.tsx, src/frontend/src/components/trade/DepositWithdrawModal/InitialContent.tsx
Update font weight to bold (700)
=> [ECO-1062] - Update white buttons' font weight

src/frontend/src/components/trade/OrdersTable.tsx
https://linear.app/econia-labs/issue/ECO-1046/what-is-this-toggle-for#comment-fb71903f
=> [ECO-1046] - Orders table remove sorting arrow

src/frontend/src/components/Header.tsx
https://linear.app/econia-labs/issue/ECO-1073/update-deposit-withdraw-font-to-match-figma
=> [ECO-1073] - Update deposit/withdraw button UI

src/frontend/src/components/AccountDetailsModal.tsx, src/frontend/src/components/MarketAccountCard.tsx, src/frontend/src/components/modals/BaseModal.tsx, src/frontend/src/components/modals/content/RegisterAccountContent.tsx, src/frontend/src/components/modals/flows/WalletButtonFlowModal.tsx, src/frontend/src/styles/globals.css
https://linear.app/econia-labs/issue/ECO-1061/add-new-account-ui-select-a-market-needs-to-be-fixed
=> [ECO-1061] - Update add new account flow

src/frontend/src/components/Button.tsx, src/frontend/src/components/modals/content/DepositWithdrawContent.tsx
https://linear.app/econia-labs/issue/ECO-1025/create-account-box-is-too-big#comment-05202e7f
=> [ECO-1025] - Update create market account button text

src/frontend/src/components/AccountDetailsModal.tsx
https://linear.app/econia-labs/issue/ECO-1061/add-new-account-ui-select-a-market-needs-to-be-fixed#comment-be7288cc
=> [ECO-1061] - Adjust add new account background gradient

src/frontend/src/components/trade/TradeHistoryTable.tsx
https://linear.app/econia-labs/issue/ECO-1077/trade-history-timedates
=> [ECO-1077] - Update trade history time/dates

src/frontend/src/components/trade/OrdersTable.tsx
https://linear.app/econia-labs/issue/ECO-1074/update-orders-ui
=> [ECO-1074] - Update orders table UI

src/frontend/src/components/AccountDetailsModal.tsx, src/frontend/src/components/Button.tsx, src/frontend/src/components/ConnectedButton.tsx, src/frontend/src/components/Header.tsx, src/frontend/src/components/MarketAccountCard.tsx, src/frontend/src/components/modals/content/DepositWithdrawContent.tsx, src/frontend/src/components/modals/content/RegisterAccountContent.tsx, src/frontend/src/components/trade/OrderEntry/LimitOrderEntry.tsx, src/frontend/src/components/trade/OrderEntry/MarketOrderEntry.tsx, src/frontend/src/contexts/ConnectWalletContext.tsx, src/frontend/src/pages/faucet/index.tsx
https://linear.app/econia-labs/issue/ECO-1073/update-button-fonts-to-match-figma
=> [ECO-1073] - Clean up button color code

src/frontend/src/components/OrderbookTable.tsx, src/frontend/src/components/TokenSymbol.tsx, src/frontend/src/components/trade/OrdersTable.tsx, src/frontend/src/components/trade/TradeHistoryTable.tsx, src/frontend/src/pages/market/[market_id].tsx
https://linear.app/econia-labs/issue/ECO-1071/fix-spacing-in-all-the-headers-on-all-screen-sizes-check-off-boxes
=> [ECO-1071] - Fix all table headers spacing

src/frontend/src/components/OrderbookTable.tsx, src/frontend/src/components/TokenSymbol.tsx, src/frontend/src/components/trade/OrdersTable.tsx, src/frontend/src/components/trade/TradeHistoryTable.tsx, src/frontend/src/pages/market/[market_id].tsx
https://linear.app/econia-labs/issue/ECO-1071/fix-spacing-in-all-the-headers-on-all-screen-sizes-check-off-boxes
https://linear.app/econia-labs/issue/ECO-1037/add-boarder-to-bottom-of-ui-to-match-the-width-of-all-the-other
=> [ECO-1071] - Update table headings spacing, padding between tables

src/frontend/src/components/AccountDetailsModal.tsx
https://linear.app/econia-labs/issue/ECO-1088/cannot-scroll-to-bottom-of-modal
=> [ECO-1088] - Fix market accounts modal scrolling bug

src/frontend/src/components/OrderbookTable.tsx, src/frontend/src/components/trade/TradeHistoryTable.tsx
https://linear.app/econia-labs/issue/ECO-1097/line-doesnt-completely-go-to-the-edge-on-trade-history-container
https://linear.app/econia-labs/issue/ECO-1096/line-is-slightly-over-hanging-on-order-book-header
=> [ECO-1097] - Fix table header bottom border

src/frontend/src/components/OrderbookTable.tsx, src/frontend/src/components/trade/OrdersTable.tsx, src/frontend/src/components/trade/TradeHistoryTable.tsx, src/frontend/src/pages/market/[market_id].tsx
https://linear.app/econia-labs/issue/ECO-1098/headers-not-fixed-on-safari
=> [ECO-1098] - Fix headers spacing on safari

README.md
Update the command description for local server to specify `pnpm`
=> Update README.md `npm` command to `pnpm`

README.md, src/frontend/.eslintrc.cjs, src/frontend/src/components/trade/TVChartContainer.tsx, src/frontend/src/contexts/AptosContext.tsx, src/frontend/src/pages/market/[market_id].tsx, src/frontend/src/store/store.ts, src/frontend/src/utils/coin.ts, src/frontend/src/utils/econia.ts, src/frontend/src/utils/formatter.tsx, src/frontend/src/utils/helpers.ts
Merge develop into main, to use main as production branch
After this PR, all branches should merge to main
This PR was generated via
```
git checkout main
git checkout -b use-main-as-prod-branch
git merge develop -Xtheirs
```
Then other PRs were merged into it
=> Merge develop into main, to use main as production branch

README.md
Add tip to install pnpm on readme
=> Add `pnpm` install tip

README.md
=> [ECO-1486] Add open source fallback README docs

src/frontend/src/pages/market/[market_id].tsx
This PR fixes the bug where a market created after Vercel deployment would not appear in the frontend.
=> [ECO-1934] fix dynamic page generation for markets
